server:
  # 服务器接受连接的端口
  port: 9000
  netty:
    # 与服务器建立 TCP 连接的等待时间
    connection-timeout: 2s
    # 如果没有数据传输，关闭 TCP 连接前的等待时间
    idle-timeout: 15s
  # 启动优雅关机
  shutdown: graceful

spring:
  application:
    name: edge-service
  lifecycle:
    # 定义 15 秒的宽限期
    timeout-per-shutdown-phase: 15s
  config:
    # 如果配置服务器可用的话，会在这里导入配置数据
    import: "optional:configserver:"
  cloud:
    config:
      # 配置服务器的 URL
      uri: http://localhost:8888
      # 等待连接配置服务器的超时时间 (毫秒)
      request-connect-timeout: 5000
      # 等待从配置服务器读取配置数据的超时时间 (毫秒)
      request-read-timeout: 5000
      # 将连接至配置服务器的失败设置为致命错误，在生产环境中设置为 true
      fail-fast: true
      retry:
        # 最大的尝试次数
        max-attempts: 6
        # Backoff 的初始重试间隔 (毫秒)
        initial-interval: 1000
        # Backoff 的最大重试间隔 (毫秒)
        max-interval: 2000
        # 计算下一次间隔的乘数
        multiplier: 1.1
    gateway:
      # 配置 HTTP 客户端的属性
      httpclient:
        # 与下游服务建立连接的时间限制 (毫秒)
        connect-timeout: 2000
        # 获取到下游服务响应的时间限制 (持续时长)
        response-timeout: 5s
        pool:
          # 连接池的类型，它的值可以是 elastic、fixed 或 disabled
          type: elastic
          # 通信通道在关闭之前的空闲时间
          max-idle-time: 15s
          # 通信通道将被关闭的时间
          max-life-time: 60s
      # 默认过滤器的列表
      default-filters:
        # 配置网关以保存会话数据，确保将请求转发至下游之前保存会话数据
        - SaveSession
        # 以网关过滤器的形式配置请求限流器
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              # 每秒钟放入桶中的令牌数量
              replenishRate: 10
              # 允许暴增到 20 个请求
              burstCapacity: 20
              # 每个请求花费多少个令牌
              requestedTokens: 1
        # 过滤器的名称
        - name: Retry
          args:
            # 最多重试 3 次
            retries: 3
            # 只对 GET 请求进行重试
            method: GET
            # 仅当遇到 5xx 错误时进行重试
            series: SERVER_ERROR
            # 仅当抛出指定异常时进行重试
            exception: java.io.IOException, java.util.concurrent.TimeoutException
            # 重试的延迟是通过 firstBackoff * (factor^n) 计算得出的
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
              factor: 2
              basedOnPreviousValue: false
      # 路由定义的列表
      routes:
        # 路由的 ID
        - id: catalog-route
          uri: ${CATALOG_SERVICE_URL:http://localhost:9001}/books
          predicates:
            # 断言形式为路径匹配
            - Path=/books/**
          filters:
            # 过滤器的名称
            - name: CircuitBreaker
              args:
                # 断路器的名称
                name: catalogCircuitBreaker
                # 当断路器处于打开状态时，要转发至该 URI
                fallbackUri: forward:/catalog-fallback
        - id: order-route
          # 来自环境变量的 URI，如果不存在，则使用默认值
          uri: ${ORDER_SERVICE_URL:http://localhost:9002}/orders
          predicates:
            - Path=/orders/**
          filters:
            # 该断路器没有配置回退 URI
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
  redis:
    # 建立连接的时间限制
    connect-timeout: 2s
    # 默认的 Redis 主机名
    host: localhost
    # 默认的 Redis 端口
    port: 6379
    # 接收到响应的时间限制
    timeout: 1s
  # 配置 Spring Session 以便于在 Redis 中存储数据
  session:
    store-type: redis
    timeout: 10m
    redis:
      namespace: polar:edge

resilience4j:
  circuitbreaker:
    configs:
      # 适用于所有断路器的默认配置 bean
      default:
        # 当断路器处于关闭状态时，记录调用次数的滑动窗口大小
        slidingWindowSize: 20
        # 当断路器处于半开状态时，允许调用的请求数
        permittedNumberOfCallsInHalfOpenState: 5
        # 当失败率高于阈值时，断路器会被打开
        failureRateThreshold: 50
        # 从打开到半开的等待时间 (毫秒)
        waitDurationInOpenState: 15000
  timelimiter:
    configs:
      # 适用于所有限时器的默认配置
      default:
        # 配置超时 (秒)
        timeoutDuration: 5s

# 为 Resilience4J 启用调试日志
logging:
  level:
    io.github.resilience4j: DEBUG
